version: 2.0
jobs:
  build:
    machine:
      enabled: true
    steps:
     - checkout
     - run:
          name: Register QMEU
          command: docker run --rm --privileged multiarch/qemu-user-static:register

     - run:
          name: Build test go docker container
          command: docker build -f go/Dockerfile -t go-aarch-container .

     - run:
         name: Test
         command: docker run --privileged go-aarch-container 