version: 2.0
jobs:
  build:
    machine:
      enabled: true
    steps:
     - checkout
     - run:
          name: Register QMEU
          command: docker run --rm --privileged multiarch/qemu-user-static:register --reset

     - run:
          name: Register QMEU
          command: docker build -f go/Dockerfile -t go-aarch-container .

     - run:
         name: Test
         command: docker run go-aarch-container