version: 2.0
jobs:
  build:
    machine:
      image: circleci/classic:2018-12
    steps:
     - checkout
     - run:
          name: Register QMEU
          command: docker run --rm --privileged multiarch/qemu-user-static:register --reset

     - run:
         name: The First Step
         command: |
           echo 'Hello World!'
           echo 'This is the delivery pipeline'